import request from '@/utils/request';
export const getForumSectionsApi = () => request.get('/forum/sections');
export const getForumPostsApi = (params) => request.get('/forum/posts', { params });
export const getForumPostDetailApi = (id) => request.get(`/forum/posts/${id}`);
export const createForumPostApi = (data) => request.post('/forum/posts', data);
export const likeForumPostApi = (id) => request.post(`/forum/posts/${id}/like`);
export const unlikeForumPostApi = (id) => request.delete(`/forum/posts/${id}/like`);
export const deleteForumPostApi = (id) => request.delete(`/forum/posts/${id}`);
export const getForumCommentsApi = (postId) => request.get('/forum/comments', { params: { postId } });
export const createForumCommentApi = (data) => request.post('/forum/comments', data);
export const likeForumCommentApi = (id) => request.post(`/forum/comments/${id}/like`);
export const unlikeForumCommentApi = (id) => request.delete(`/forum/comments/${id}/like`);
export const deleteForumCommentApi = (id) => request.delete(`/forum/comments/${id}`);
export const topForumPostApi = (id) => request.post(`/admin/forum/posts/${id}/top`);
export const cancelTopForumPostApi = (id) => request.post(`/admin/forum/posts/${id}/cancel-top`);
